/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import Napakalaki.CultistPlayer;
import Napakalaki.Napakalaki;
import Napakalaki.Player;
import Napakalaki.Treasure;

/**
 *
 * @author braulio
 */
public class PlayerView extends javax.swing.JPanel {

    private Player playerModel;
    private Napakalaki napakalakyModel;
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }
    
    public void setPlayer(Player p){
        playerModel = p;
        name.setText(this.playerModel.getName());
        level.setText(Integer.toString(this.playerModel.getLevels()));
        if(this.playerModel.isDead())
            dead.setText("Yes");
        else
            dead.setText("No");
        fillTreasursePanel(hiddenTreasures, playerModel.getHiddenTreasures());
        fillTreasursePanel(visibleTreasures, playerModel.getVisibleTreasures());
        cultistView1.setCultist(playerModel);
        repaint();
        revalidate();
    }
    
    public void setNapakalaki(Napakalaki n){
        this.napakalakyModel = n;
    }
    
    public void fillTreasursePanel(JPanel aPanel, ArrayList<Treasure> aList){
        // Eliminar información antigua
        aPanel.removeAll();
        // Se recorren los tesoros y se añaden sus vistas al panel
        for(Treasure t:aList){
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTresaure(t);
            aTreasureView.setVisible(true);
            aPanel.add(aTreasureView);
        }
        // se fuerza la actualización visual del panel
        
        aPanel.repaint();
        aPanel.revalidate();
    }
    
    public ArrayList<Treasure> getSelectedTreasures(JPanel aPanel){
        // Se recorren los tesoros que contiene el panel,
        // almacenando en un vector aquellosque están seleccionados.
        // Finalmente se devuelve dicho vector
        
        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for(Component c:aPanel.getComponents()){
            tv = (TreasureView)c;
            if(tv.isSelected())
                output.add(tv.getTreasure());
        }
        
        return output;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dead = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        makeVisibleButton = new javax.swing.JButton();
        discardTreasureButton = new javax.swing.JButton();
        buyLevelsButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        visibleTreasures = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hiddenTreasures = new javax.swing.JPanel();
        cultistView1 = new GUI.CultistView();

        setMaximumSize(new java.awt.Dimension(508, 460));
        setMinimumSize(new java.awt.Dimension(508, 460));

        jLabel1.setText("Player name");

        jLabel2.setText("Level");

        jLabel3.setText("Dead?");

        jLabel4.setText("Visible Treasures");

        jLabel5.setText("Hidden Treasures");

        makeVisibleButton.setText("Make Visible");
        makeVisibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeVisibleButtonActionPerformed(evt);
            }
        });

        discardTreasureButton.setText("Discard Treasure");
        discardTreasureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardTreasureButtonActionPerformed(evt);
            }
        });

        buyLevelsButton.setText("Buy Levels");
        buyLevelsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyLevelsButtonActionPerformed(evt);
            }
        });

        visibleTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        visibleTreasures.setMaximumSize(new java.awt.Dimension(32767, 102));
        jScrollPane2.setViewportView(visibleTreasures);

        hiddenTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hiddenTreasures.setMaximumSize(new java.awt.Dimension(32767, 102));
        jScrollPane3.setViewportView(hiddenTreasures);

        cultistView1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dead, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(127, 127, 127))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buyLevelsButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(makeVisibleButton)))
                                        .addGap(18, 18, 18)
                                        .addComponent(discardTreasureButton)))
                                .addGap(0, 137, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cultistView1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dead, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cultistView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeVisibleButton)
                    .addComponent(discardTreasureButton)
                    .addComponent(buyLevelsButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void makeVisibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeVisibleButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        napakalakyModel.makeTreasuresVisibles(selHidden);
        setPlayer(napakalakyModel.getCurrentPlayer());
    }//GEN-LAST:event_makeVisibleButtonActionPerformed

    private void buyLevelsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyLevelsButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> selVisible = getSelectedTreasures(visibleTreasures);
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        playerModel.buyLevels(selVisible, selHidden);
        setPlayer(this.napakalakyModel.getCurrentPlayer());
        
    }//GEN-LAST:event_buyLevelsButtonActionPerformed

    private void discardTreasureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardTreasureButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> selVisible = getSelectedTreasures(visibleTreasures);
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        for(Treasure t:selHidden){
            this.playerModel.discardHiddenTreasure(t);
        }
        for(Treasure t:selVisible){
            this.playerModel.discardVisibleTreasure(t);
        }
        this.setPlayer(napakalakyModel.getCurrentPlayer());
    }//GEN-LAST:event_discardTreasureButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyLevelsButton;
    private GUI.CultistView cultistView1;
    private javax.swing.JLabel dead;
    private javax.swing.JButton discardTreasureButton;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel level;
    private javax.swing.JButton makeVisibleButton;
    private javax.swing.JLabel name;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables

    void DisableBuyLevels() {
        buyLevelsButton.setEnabled(false);
    }

    void DisableMakeVisible() {
        makeVisibleButton.setEnabled(false);
    }
    
    void DisableDiscardTreasure(){
        this.discardTreasureButton.setEnabled(false);
    }
    
    void EnableBuyLevels() {
        buyLevelsButton.setEnabled(true);
    }

    void EnableMakeVisible() {
        makeVisibleButton.setEnabled(true);
    }
    
    void EnableDiscardTreasure(){
        this.discardTreasureButton.setEnabled(true);
    }
    
    public void DisableAllButtons(){
        buyLevelsButton.setEnabled(false);
        makeVisibleButton.setEnabled(false);
        discardTreasureButton.setEnabled(false);
    }
            
}
